kind: pipeline
type: docker
name: Test

steps:
  - name: run tests
    image: alpine
    commands:
      - apk add --update nodejs npm yarn
      - yarn install
      - yarn run tsc
      - yarn run eslint

---

kind: pipeline
type: ssh
name: deploy

trigger:
  branch:
    - main

server:
  host:
    from_secret: host
  user: deploy
  password:
    from_secret: password

steps:
  - name: deploy
    commands:
      - cd /srv/docker/
      - docker-compose up -d
