name: Lint and Format Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/bun@v1
        with:
          version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Run lint script
        run: bun run lint

